### ISSUE TITLE
导出的zip压缩包有问题

### ISSUE THREAD

**Issue by mengyvleihen** [lihe07/bilibili_comics_downloader#10]
辛苦大佬制作导出zip的功能，不过我尝试了一下
发现不管是bandizip还是最新的稳定版7zip都显示为不支持的压缩算法，无法解压
或许改为直接导出为文件夹更好？

**Comment by mengyvleihen** [comment]
对了 ，大佬，能不能再增加一个校验功能？
因为我下载话数比较多的漫画时发现它很容易卡死，很担心会因此有缺页，
只需要每次下载时对每话的页数进行校验应该就够了吧，
如果本来就有当我没说。

**Comment by lihe07** [comment]
校验想到了，包括对单个图片的校验和页数的校验。
ZIP包的确使用了非常规（大概）的压缩算法，ZSTD
我会在下个版本改回普通的Storage

**Comment by lihe07** [comment]
咕了一段时间，这个问题在0.1.7修复了
