### ISSUE TITLE
可以加入限免漫画的下载功能😁😁😁

### ISSUE THREAD

**Issue by AsuZSH** [lihe07/bilibili_comics_downloader#13]
最近在看超炮，但是他限免额额额，下载就失败了
要不加个小功能呗

URL：
https://manga.bilibili.com/detail/mc26550

**Comment by lihe07** [comment]
不知道是不是错过了，我这里没截到限免的包
工具判断是否锁定是根据 `isLock` 字段判断的，如果遇到其他限免漫画我会继续处理这个issue

**Comment by AsuZSH** [comment]
好嘞，辛苦你啦！

**Comment by zhongfly** [comment]
> 不知道是不是错过了，我这里没截到限免的包 工具判断是否锁定是根据 `isLock` 字段判断的，如果遇到其他限免漫画我会继续处理这个issue

限免应该是根据`is_in_free`来决定的，不太清楚是否发生改变

**Comment by tassss2** [comment]
一般限免是可以下载，但新人限免是不能

**Comment by lihe07** [comment]
Addressed
