### ISSUE TITLE
部分章节标题获取失败

### ISSUE THREAD

**Issue by AsuZSH** [lihe07/bilibili_comics_downloader#14]
恳请作者尽快修复

测试命令：`bcdown search mc25969`
终端：`Windows terminal`
测试结果：

ℹ 加载配置文件：C:\Users\asuzsh\Documents\bcdown/config.toml
✔ 漫画标题：碧蓝之海
✔ 漫画作者 / 出版社：井上坚二,吉冈公威,讲谈社
✔ 漫画标签：都市
✔ 漫画章节：

    0 - 可用 -
    0.4 - 可用 - 出版社声明
    1 - 可用 -
    2 - 可用 -
    3 - 可用 -
    4 - 可用 -
    5 - 可用 -
    6 - 可用 -
    7 - 可用 -
    8 - 可用 -
    8.1 - 可用 -
    9 - 可用 -
    10 - 可用 -
    11 - 可用 -
    12 - 可用 -
    12.1 - 可用 -
    13 - 可用 -
    14 - 可用 -
    15 - 可用 -
    16 - 可用 -
    17 - 可用 -
    18 - 可用 -
    19 - 可用 -
    20 - 可用 -
    21 - 可用 -
    21.1 - 可用 -
    22 - 可用 -
    23 - 可用 -
    24 - 可用 -
    25 - 可用 -
    25.1 - 可用 -
    26 - 可用 -
    27 - 锁定 -
    28 - 可用 -
    28.1 - 可用 -
    29 - 可用 -
    30 - 可用 -
    31 - 可用 -
    32 - 可用 -
    33 - 可用 -
    34 - 可用 -
    35 - 可用 -
    36 - 可用 -
    37 - 可用 -
    38 - 可用 -
    39 - 可用 -
    40 - 可用 -
    41 - 可用 -
    41.1 - 可用 -
    42 - 可用 -
    43 - 可用 -
    44 - 可用 -
    45 - 可用 -
    46 - 可用 -
    47 - 可用 -
    47.1 - 可用 -
    48 - 可用 -
    49 - 可用 -
    50 - 可用 -
    51 - 可用 -
    52 - 可用 -
    53 - 可用 -
    54 - 可用 -
    56 - 可用 -
    57 - 可用 -
    58 - 可用 - 逃跑之
    59 - 可用 - Fun Diving
    60 - 可用 - 母亲
    61 - 可用 - 暑假结束后
    62 - 可用 - 联谊Round2
    63 - 可用 - 捡栗子
    64 - 可用 - 中奖
    65 - 可用 - 狗
    66 - 可用 - 作战会议
    68 - 可用 - 第一食堂
    69 - 可用 - 再次登陆冲绳
    70 - 可用 - 再次登陆冲绳·背后的故事
    71 - 可用 - 第二天的混乱
    72 - 可用 - 特别篇
    73 - 可用 - 樱子的旅途
    74 - 可用 - 嫉妒！
    75 - 可用 - 喜欢的人
    76 - 可用 - 回程的两人
    77 - 可用 - 死亡游戏
    78 - 可用 - 深夜体操
    79 - 可用 - 哀伤的another round
    80 - 可用 - 改推挑战
    81 - 可用 - Hypnosis Crisis 催眠危机
    82 - 可用 - 烂醉乒乓
    83 - 可用 - 盛装打扮
    84 - 可用 - 山本真一郎的灾难
    85 - 可用 - 结婚派对

**Comment by lihe07** [comment]
最近在忙考试，没看到Github的通知
这个应该是由B漫本身未给出标题导致的，
我考虑的修复方案是：如果B漫返回的标题为空，则为其生成一个类似于 `第 _ 话` 的占位标题防止出Bug
您看是否合适？

**Comment by AsuZSH** [comment]
可以啊，不过在网站上有标题哎，蛮奇怪的也

**Comment by lihe07** [comment]
![image](https://user-images.githubusercontent.com/53819558/176991696-81c7d455-768c-45b1-b31f-f37181dbd5ff.png)

处理完了，没有其他问题的话下一版本更新
