### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by dobefore** [lihe07/bilibili_comics_downloader#28]
有这方面的必要吗，有的话，我愿意抽出时间提交个PR。

CI: run cmds cargo fmt,clippy,build check

CD: 发布release到GitHub：平台：windows x64, linux x64,macos,arm64(可能)

**Comment by lihe07** [comment]
感谢！
确实有这方面的需要（但是没有专门研究过rust的Github actions）
如果可以的话，麻烦您开个pr吧！

**Comment by dobefore** [comment]
好的。我会在闲暇时间完成，时间上可能会是几天，希望能接受。

**Comment by lihe07** [comment]
> 好的。我会在闲暇时间完成，时间上可能会是几天，希望能接受。

没问题，感谢
