### ISSUE TITLE
bug  fetch 报错消息

### ISSUE THREAD

**Issue by cocoadi** [lihe07/bilibili_comics_downloader#5]
命令：

.\bcdown fetch 28426

[00:01:21] ###-------------------------------------       2/33      135 KB / s

消息：
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom {
kind: UnexpectedEof, error: IncompleteBody }) }', src\lib\network.rs:253:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

PSVersion = 5.1.19041.1682
ℹ 加载配置文件：C:\Users\Administrator\Documents\bcdown/config.toml
ℹ 缓存目录：D:\bcdown/cache
ℹ 缓存目录大小：1 GB
ℹ 默认下载目录：D:\bcdown

重复执行4次，每次执行都能下载一部分，然后报错。最后一次进度条走到了100%，成功下载。

**Comment by lihe07** [comment]
出现panic的频率高吗？有时候会因为网络波动请求失败的现象，我怕无效数据影响程序，就让程序在遇到问题的时候强制退出了。
一般来说这个现象只会偶尔出现

**Comment by lihe07** [comment]
这个问题在v0.1.4版本里修复了
