### ISSUE TITLE
大佬能开发一个新功能吗？

### ISSUE THREAD

**Issue by mengyvleihen** [lihe07/bilibili_comics_downloader#7]
大佬能让这个工具支持直接导出为zip压缩包或者按顺序重命名好图片名也行，主要是手机还是不太方便阅读epub文件，而且压缩包的话，就能配合Comic Screen这个软件看条漫了。

**Comment by lihe07** [comment]
好的！收到需求，我预计这两天内搞定

**Comment by lihe07** [comment]
开发完毕，下一个版本补上
